### ISSUE TITLE
Bot rejecting valid url

### ISSUE THREAD

**Issue by vahi-moses** [ScriptyCord/ScriptyCord#11]
Hello, I found url that does not work event though it od correct: https://m.youtube.com/watch?v=H7NsEv_0iOk
![IMG_20220923_175720](https://user-images.githubusercontent.com/32983684/192002875-89a321b2-2f57-4a8b-88f8-e7f0f75fe324.jpg)

**Comment by TheKornyOne** [comment]
Fixed in https://github.com/ScriptyCord/ScriptyCord/commit/82e1fc2a3b154e1f62594ad416ec4b741ef47b59
